//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commander
    {
        public Commander()
        {
            this.ShipBuild = new HashSet<ShipBuild>();
        }
    
        public string Name { get; set; }
        public string Password { get; set; }
        public string AutoLogin { get; set; }
        public bool SiriusDiscount { get; set; }
        public bool ShowModulePrices { get; set; }
    
        public virtual ICollection<ShipBuild> ShipBuild { get; set; }
    }
}
