//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EliteContext : DbContext
    {
        public EliteContext()
            : base("name=EliteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commander> Commander { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Ship> Ship { get; set; }
        public virtual DbSet<ShipBuild> ShipBuild { get; set; }
        public virtual DbSet<ShipModuleBuild> ShipModuleBuild { get; set; }
        public virtual DbSet<ShipModuleConfiguration> ShipModuleConfiguration { get; set; }
    
        public virtual ObjectResult<SelectShipBuilds_Result> SelectShipBuilds(string shipName)
        {
            var shipNameParameter = shipName != null ?
                new ObjectParameter("ShipName", shipName) :
                new ObjectParameter("ShipName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectShipBuilds_Result>("SelectShipBuilds", shipNameParameter);
        }
    }
}
