//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.ShipModuleBuild = new HashSet<ShipModuleBuild>();
        }
    
        public int ID { get; set; }
        public string ShipSpecific { get; set; }
        public string Section { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public int Class { get; set; }
        public string Rating { get; set; }
        public Nullable<double> M { get; set; }
        public Nullable<double> P { get; set; }
        public string Attributes { get; set; }
        public Nullable<double> FuelMultiplier { get; set; }
        public Nullable<double> FuelPower { get; set; }
        public Nullable<double> MaxFuel { get; set; }
        public Nullable<double> Mass { get; set; }
        public Nullable<double> Power { get; set; }
        public Nullable<int> Boost { get; set; }
        public double Price { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> DamagePerSecond { get; set; }
        public Nullable<int> ThermalLoad { get; set; }
        public string WeaponMount { get; set; }
        public string WeaponType { get; set; }
        public Nullable<double> RateOfFire { get; set; }
        public string Penetration { get; set; }
        public string Ammo { get; set; }
        public Nullable<double> MinMass { get; set; }
        public Nullable<int> OptimalMass { get; set; }
        public Nullable<int> MaxMass { get; set; }
        public Nullable<double> MinMultiplier { get; set; }
        public Nullable<double> OptMultiplier { get; set; }
        public Nullable<double> MaxMultiplier { get; set; }
        public Nullable<int> Armour { get; set; }
        public Nullable<double> ScoopRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipModuleBuild> ShipModuleBuild { get; set; }
    }
}
