//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipModuleBuild
    {
        public int ID { get; set; }
        public int ShipBuildID { get; set; }
        public int ShipModuleConfigurationID { get; set; }
        public int ModuleID { get; set; }
        public bool PowerStatus { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ShipBuild ShipBuild { get; set; }
        public virtual ShipModuleConfiguration ShipModuleConfiguration { get; set; }
    }
}
