//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipBuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipBuild()
        {
            this.ShipModuleBuild = new HashSet<ShipModuleBuild>();
        }
    
        public int ID { get; set; }
        public string CommanderName { get; set; }
        public string Name { get; set; }
        public string ShipName { get; set; }
    
        public virtual Commander Commander { get; set; }
        public virtual Ship Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipModuleBuild> ShipModuleBuild { get; set; }
    }
}
