//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public Ship()
        {
            this.ShipBuild = new HashSet<ShipBuild>();
            this.ShipModuleConfiguration = new HashSet<ShipModuleConfiguration>();
        }
    
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public int Price { get; set; }
        public int Size { get; set; }
        public int Speed { get; set; }
        public int Boost { get; set; }
        public int Agility { get; set; }
        public int Shields { get; set; }
        public int Armour { get; set; }
        public int Mass { get; set; }
        public Nullable<int> MassLock { get; set; }
        public Nullable<int> HullPrice { get; set; }
    
        public virtual ICollection<ShipBuild> ShipBuild { get; set; }
        public virtual ICollection<ShipModuleConfiguration> ShipModuleConfiguration { get; set; }
    }
}
